export const SCENARIOS = {
  startup: {
    name: "Early-Stage Startup",
    description: "Tech startup with basic security",
    controls: {
      security_policy: false,
      policy_review: false,
      roles_responsibilities: false,
      firewall: "partial",
      network_monitoring: false,
      segmentation: false,
      antivirus: true,
      patch_management: false,
      device_encryption: false,
      mfa: false,
      access_control: false,
      privileged_access: false,
      ir_plan: false,
      ir_testing: false,
      breach_notification: false,
      backup_strategy: false,
      recovery_testing: false,
      ransomware_protection: false,
      security_training: false,
      phishing_tests: false,
      policy_acknowledgment: false,
    },
  },
  saas: {
    name: "SaaS Company",
    description: "Mature SaaS with strong controls",
    controls: {
      security_policy: true,
      policy_review: true,
      roles_responsibilities: true,
      firewall: "full",
      network_monitoring: true,
      segmentation: true,
      antivirus: true,
      patch_management: true,
      device_encryption: true,
      mfa: true,
      access_control: true,
      privileged_access: true,
      ir_plan: true,
      ir_testing: true,
      breach_notification: true,
      backup_strategy: true,
      recovery_testing: true,
      ransomware_protection: true,
      security_training: true,
      phishing_tests: true,
      policy_acknowledgment: true,
    },
  },
  legacy: {
    name: "Legacy Enterprise",
    description: "Large organization with legacy systems",
    controls: {
      security_policy: true,
      policy_review: true,
      roles_responsibilities: true,
      firewall: "full",
      network_monitoring: true,
      segmentation: false,
      antivirus: true,
      patch_management: true,
      device_encryption: false,
      mfa: false,
      access_control: true,
      privileged_access: true,
      ir_plan: true,
      ir_testing: false,
      breach_notification: true,
      backup_strategy: true,
      recovery_testing: true,
      ransomware_protection: false,
      security_training: true,
      phishing_tests: false,
      policy_acknowledgment: true,
    },
  },
  bank: {
    name: "Financial Institution",
    description: "Regulated bank with compliance focus",
    controls: {
      security_policy: true,
      policy_review: true,
      roles_responsibilities: true,
      firewall: "full",
      network_monitoring: true,
      segmentation: true,
      antivirus: true,
      patch_management: true,
      device_encryption: true,
      mfa: true,
      access_control: true,
      privileged_access: true,
      ir_plan: true,
      ir_testing: true,
      breach_notification: true,
      backup_strategy: true,
      recovery_testing: true,
      ransomware_protection: true,
      security_training: true,
      phishing_tests: true,
      policy_acknowledgment: true,
    },
  },
}
